AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trader_pricer

  Sample SAM Template for trader_pricer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # MyLibLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     ContentUri: my_lib_layer
  #     CompatibleRuntimes:
  #       - python3.8
  #   Metadata:
  #     BuildMethod: python3.8 # this is where magic happen, sam build command will read requirements.txt file and download libraries
  PricerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pricer/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-numpy:17
      # Layers:
      #   - !Ref MyLibLayer
      Events:
        Pricer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /price
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PricerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/price/"
  PricerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PricerFunction.Arn
  PricerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PricerFunctionRole.Arn
